export const projects = [
    {
        name: 'Time Tracker',
        url: 'https://vyper248.github.io/time-tracker/',
        description: 'Basic app for tracking time. Designed to help track time worked during the week, which I thought could be helpful when on flexible working hours.',
        x: 80,
        y: 800,
        offset: 50,
        width: 200,
        svg: 'building7.svg',        
    },
    {
        name: 'Food Planner',
        url: 'https://vyper248.github.io/food-planner/',
        description: 'I love to be organised, so I created an app to help plan out meals and show me what food I need to order.',
        x: 300,
        y: 800,
        offset: 50,
        width: 200,
        svg: 'building14.svg',        
    },
    {
        name: 'Budget App',
        url: 'https://vyper248.github.io/budget-app/',
        description: 'Fairly simple budgetting app that I\'ve been actively using to keep track of my finances.',
        x: 300,
        y: 800,
        offset: 50,
        width: 200,
        svg: 'building9.svg',        
    },
    {
        name: 'Reddit React App',
        url: 'https://vyper248.github.io/new-reddit/#/PS4',
        description: 'Second React app I created, this time using React-Router for navigation. It\'s another version of Reddit, this time more in-line with the Reddit website, with more sorting options. Currently using pre-configured sub list. Also decided to create this with a dark theme.',
        x: 150,
        y: 300,
        offset: 48,
        width: 200,
        svg: 'building3.svg',        
    },
    {
        name: 'Watching Together',
        url: 'https://watch-together.onrender.com/',
        description: 'A simple website using Socket.io to allow 2 people to watch the same show or movie together. Events like pausing, playing and seeking are synced between the 2 users. There\'s also a text feature to allow communication without taking focus away from the screen.',
        x: 450,
        y: 300,
        offset: 48,
        width: 200,
        svg: 'building4.svg',        
    },
    {
        name: 'Code Builder',
        url: 'https://code-builder.onrender.com/',
        description: 'I thought it would be nice to have a tool for creating various templates for getting started with different projects, such as NodeJS or React, with or without Redux etc.',
        x: 750,
        y: 500,
        offset: 48,
        width: 200,
        svg: 'building7.svg',        
    },
    {
        name: 'Chat Room',
        url: 'https://chat-room-we1h.onrender.com/',
        description: 'Basic chat room using socket.io, with support for different rooms and multiple users.',
        x: 950,
        y: 500,
        offset: 48,
        width: 200,
        svg: 'building8.svg',        
    },
    {
        name: 'Forest Finder',
        url: 'https://forest-finder.onrender.com/',
        description: 'An older website I created as part of a course. Can login, add new forests, leave comments and ratings. I added an integration with Google Maps, but it hasn\'t been updated in a while so no longer works.',
        x: 1150,
        y: 500,
        offset: 48,
        width: 200,
        svg: 'building7.svg',        
    },
];