//good buildings - 3,4,7,8,9,14
export const projects = [
    //Latest
    {
        name: 'Gaming Commerce',
        url: 'https://gaming-commerce.netlify.app/',
        description: 'Fake E-Commerce website created to practise with Stripe payments, GraphQL, Redux Toolkit and Serverless Functions.',
        x: 0,
        y: 0,
        offset: 50,
        width: 200,
        group: 'Latest',
        svg: 'building8.svg',     
        screenshot: 'GamingCommerce.png',
        displaySize: 3
    },
    {
        name: 'Time Tracker',
        url: 'https://vyper248.github.io/time-tracker/',
        description: 'Basic app for tracking time. Designed to help track time worked during the week, which I thought could be helpful when on flexible working hours.',
        x: 0,
        y: 0,
        offset: 50,
        width: 200,
        group: 'Latest',
        svg: 'building7.svg',    
        screenshot: 'TimeTracker.png',
        displaySize: 3    
    },
    {
        name: 'Food Planner',
        url: 'https://vyper248.github.io/food-planner/',
        description: 'I love to be organised, so I created an app to help plan out meals and show me what food I need to order.',
        x: 0,
        y: 0,
        offset: 50,
        width: 200,
        group: 'Latest',
        svg: 'building14.svg',  
        screenshot: 'FoodPlanner.png',
        displaySize: 3      
    },
    {
        name: 'Budget App',
        url: 'https://vyper248.github.io/budget-app/',
        description: 'Fairly simple budgetting app that I\'ve been actively using to keep track of my finances.',
        x: 0,
        y: 0,
        offset: 50,
        width: 200,
        group: 'Latest',
        svg: 'building9.svg',     
        screenshot: 'Budget.png',
        displaySize: 3   
    },
    {
        name: 'Reddit React App',
        url: 'https://vyper248.github.io/new-reddit/#/PS5/new',
        description: 'My own version of Reddit, but without the clutter. Created with a dark theme and expanded to include more features over time.',
        x: 0,
        y: 0,
        offset: 48,
        width: 200,
        group: 'Latest',
        svg: 'building3.svg',      
        screenshot: 'NewReddit.png',
        displaySize: 3  
    },
    //Old Projects
    {
        name: 'Care Home Management',
        url: 'https://care-home-management.onrender.com',
        description: 'One of the first large websites I made after learning React (actually recreated from an older JS/PHP/SQL website I made). Plenty of mistakes and things I\'d do differently, but it functioned well and was used for a care home I worked for to increase productivity.\nRender.com takes time to open.',
        x: 0,
        y: 0,
        offset: 48,
        width: 200,
        group: 'Old Projects',
        svg: 'building3.svg',        
        displaySize: 2
    },
    {
        name: 'Watching Together',
        url: 'https://watch-together.onrender.com/',
        description: 'A simple website using Socket.io to allow 2 people to watch the same show or movie together. Events like pausing, playing and seeking are synced between the 2 users. There\'s also a text feature to allow communication without taking focus away from the screen.\nRender.com takes time to open.',
        x: 0,
        y: 0,
        offset: 48,
        width: 200,
        group: 'Old Projects',
        svg: 'building4.svg',        
        displaySize: 2
    },
    {
        name: 'Chat Room',
        url: 'https://chat-room-we1h.onrender.com/',
        description: 'Basic chat room using socket.io, with support for different rooms and multiple users.\nRender.com takes time to open.',
        x: 0,
        y: 0,
        offset: 48,
        width: 200,
        group: 'Old Projects',
        svg: 'building8.svg', 
        displaySize: 2       
    },
    {
        name: 'Forest Finder',
        url: 'https://forest-finder.onrender.com/',
        description: 'An older website I created as part of a course. Can login, add new forests, leave comments and ratings. I added an integration with Google Maps, but it hasn\'t been updated in a while so no longer works.\nRender.com takes time to open.',
        x: 0,
        y: 0,
        offset: 48,
        width: 200,
        group: 'Old Projects',
        svg: 'building7.svg',   
        displaySize: 2     
    },
    {
        name: 'Advent of Code',
        url: 'https://vyper248.github.io/advent-of-code-2018/',
        description: 'My solutions to the Advent of Code 2018 challenges. Not trying to get on the leaderboards with this, which would require getting up far too early each day, just something to do for fun.',
        x: 0,
        y: 0,
        offset: 48,
        width: 200,
        group: 'Old Projects',
        svg: 'building9.svg',    
        displaySize: 2    
    },
    //Very Old Projects
    {
        name: 'Basic Image Gallery',
        url: 'https://vyper248.github.io/oldPortfolio/OldStuff/imageGallery.html',
        description: 'A very simple image gallery.',
        x: 0,
        y: 0,
        offset: 48,
        width: 200,
        group: 'Very Old Projects',
        svg: 'building14.svg',        
    },
    {
        name: 'Spyrograph',
        url: 'https://vyper248.github.io/oldPortfolio/OldStuff/spyrograph.html',
        description: 'A basic spyrograph creator. Can create multiple circular paths, each with a rotator which draws the line. These can have different speeds / rotations / colours etc. Global speed can be changed for faster viewing. Uses P5.',
        x: 0,
        y: 0,
        offset: 48,
        width: 200,
        group: 'Very Old Projects',
        svg: 'building3.svg',        
    },
    {
        name: 'Tic Tac Toe',
        url: 'https://vyper248.github.io/oldPortfolio/OldStuff/TicTacToe.html',
        description: 'Basic 2 player Tic Tac Toe game. Requires 2 people taking turns.',
        x: 0,
        y: 0,
        offset: 48,
        width: 200,
        group: 'Very Old Projects',
        svg: 'building8.svg',        
    },
    {
        name: 'Tic Tac Toe (2)',
        url: 'https://vyper248.github.io/oldPortfolio/OldStuff/TicTacToe2.html',
        description: 'Tic Tac Toe against the AI. Also includes option to adjust the board size, although you can\'t really win with large boards!',
        x: 0,
        y: 0,
        offset: 48,
        width: 200,
        group: 'Very Old Projects',
        svg: 'building4.svg',        
    },
    {
        name: 'Colour Guessing Game',
        url: 'https://vyper248.github.io/oldPortfolio/OldStuff/colorGuessing.html',
        description: 'Simple game to test how well you know RGB colours. Can you guess the correct one?',
        x: 0,
        y: 0,
        offset: 48,
        width: 200,
        group: 'Very Old Projects',
        svg: 'building3.svg',        
    },
    {
        name: 'To Do List',
        url: 'https://vyper248.github.io/oldPortfolio/OldStuff/toDoList.html',
        description: 'Basic To Do List. Can add, edit and delete items, and of course mark them as complete or not. Data is stored in local storage, no server used (just for testing).',
        x: 0,
        y: 0,
        offset: 48,
        width: 200,
        group: 'Very Old Projects',
        svg: 'building7.svg',        
    },
    {
        name: 'Gradient Generator',
        url: 'https://vyper248.github.io/oldPortfolio/CompleteWebDevCourse/backgroundGenerator.html',
        description: 'This project allows the creation of linear gradients. I added to it by including sliders to adjust the percentages as well as the ability to add more colours.',
        x: 0,
        y: 0,
        offset: 48,
        width: 200,
        group: 'Very Old Projects',
        svg: 'building4.svg',        
    },
    //Experiments
    {
        name: 'Random Walkers',
        url: 'https://vyper248.github.io/oldPortfolio/OldStuff/randomWalker.html',
        description: 'Playing around with randomness to create walkers. Has a few controls for display, size, speed and random type. Uses P5.',
        x: 0,
        y: 0,
        offset: 48,
        width: 200,
        group: 'Experiments',
        svg: 'building3.svg',        
    },
    {
        name: 'Perlin Noise',
        url: 'https://vyper248.github.io/oldPortfolio/OldStuff/noise.html',
        description: 'Experimenting with different ways of using and displaying noise, including a simple wave, a flow field and a 3D representation. Uses P5.',
        x: 0,
        y: 0,
        offset: 48,
        width: 200,
        group: 'Experiments',
        svg: 'building8.svg',        
    },
    {
        name: 'Stick Figure',
        url: 'https://vyper248.github.io/oldPortfolio/OldStuff/myStickFigure.html',
        description: 'Experimenting with creating an animatable stick figure. Can create and save different poses and use those to create an animation. But it was never completed. Uses P5.',
        x: 0,
        y: 0,
        offset: 48,
        width: 200,
        group: 'Experiments',
        svg: 'building7.svg',        
    },
    {
        name: 'Forces',
        url: 'https://vyper248.github.io/oldPortfolio/OldStuff/forces.html',
        description: 'Messing around with different forces such as wind, drag, friction and gravity. Includes a few other options to play with, although collision was just basic with no real physics involved, so doesn\'t look great. Uses P5.',
        x: 0,
        y: 0,
        offset: 48,
        width: 200,
        group: 'Experiments',
        svg: 'building4.svg',        
    },
];