export const skills = [
    {
        name: 'JavaScript',
        url: '',
        description: '',
        x: 0,
        y: 0,
        offset: 50,
        offsetX: 30,
        width: 150,
        group: 'Experienced',
        svg: 'javascript.svg',        
    },
    {
        name: 'HTML5',
        url: '',
        description: '',
        x: 0,
        y: 0,
        offset: 50,
        offsetX: 30,
        width: 150,
        group: 'Experienced',
        svg: 'html5.svg',        
    },
    {
        name: 'CSS3',
        url: '',
        description: '',
        x: 0,
        y: 0,
        offset: 50,
        offsetX: 30,
        width: 150,
        group: 'Experienced',
        svg: 'css3.svg',        
    },
    {
        name: 'React',
        url: '',
        description: '',
        x: 0,
        y: 0,
        offset: 50,
        offsetX: 30,
        width: 150,
        group: 'Experienced',
        svg: 'react.svg',        
    },
    {
        name: 'Redux Toolkit',
        url: '',
        description: '',
        x: 0,
        y: 0,
        offset: 50,
        offsetX: 30,
        width: 150,
        group: 'Experienced',
        svg: 'redux-toolkit.svg',        
    },
    {
        name: 'Styled-Components',
        url: '',
        description: '',
        x: 0,
        y: 0,
        offset: 50,
        offsetX: 50,
        width: 150,
        group: 'Experienced',
        svg: 'styled-components.svg',        
    },
    //Learning
    {
        name: 'TypeScript',
        url: '',
        description: '',
        x: 0,
        y: 0,
        offset: 50,
        offsetX: 30,
        width: 150,
        group: 'Learning',
        svg: 'typescript.svg',        
    },
    {
        name: 'SolidJS',
        url: '',
        description: '',
        x: 0,
        y: 0,
        offset: 50,
        offsetX: 30,
        width: 150,
        group: 'Learning',
        svg: 'solidJS.svg',        
    },
    {
        name: 'NextJS',
        url: '',
        description: '',
        x: 0,
        y: 0,
        offset: 50,
        offsetX: 30,
        width: 150,
        group: 'Learning',
        svg: 'nextJS.svg',        
    },
    //Older Skills
    {
        name: 'PHP',
        url: '',
        description: '',
        x: 0,
        y: 0,
        offset: 50,
        offsetX: 30,
        width: 150,
        group: 'Older Skills',
        svg: 'php.svg',        
    },
    {
        name: 'SQL',
        url: '',
        description: '',
        x: 0,
        y: 0,
        offset: 50,
        offsetX: 30,
        width: 150,
        group: 'Older Skills',
        svg: 'sql.svg',        
    },
];